library(reticulate)
use_python("/usr/bin/python3")
Sys.setenv(RETICULATE_PYTHON = "/usr/bin/python3")
reticulate::py_config()
#Importa el frustra - seteta los directorios:
library(frustratometeR)
#Los path son diferentes para cada simulacion
PdbsDir <- "/home/titanx1/Documents/sims/frustra/rfah/concatenadas/"
ResultsDir <- "/home/titanx1/Documents/sims/frustra/rfah/concatenadas/Results/"
OrderList <-c()
for(i in as.numeric(0):as.numeric(11994)){OrderList <- c(OrderList, paste("pdb",i,".pdb",sep=""))}
Dynamic_sing <- dynamic_frustration(PdbsDir = PdbsDir, ResultsDir = ResultsDir, OrderList = OrderList,
                                    GIFs = FALSE, Mode = "singleresidue")
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 50, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 51, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 52, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 88, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 89, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 126, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 128, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 140, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 145, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 146, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 81, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 92, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 93, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 116, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 117, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 118, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 127, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 131, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 138, Chain = "X", Graphics = TRUE)
Dynamic_sing <- dynamic_res(Dynamic = Dynamic_sing, Resno = 139, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_frustration(PdbsDir = PdbsDir, ResultsDir = ResultsDir, OrderList = OrderList,
                                    GIFs = FALSE, Mode = "mutational")
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 50, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 51, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 52, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 88, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 89, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 126, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 128, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 140, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 145, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 146, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 81, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 92, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 93, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 116, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 117, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 118, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 127, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 131, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 138, Chain = "X", Graphics = TRUE)
Dynamic_mutational <- dynamic_res(Dynamic = Dynamic_mutational, Resno = 139, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_frustration(PdbsDir = PdbsDir, ResultsDir = ResultsDir, OrderList = OrderList,
                                    GIFs = FALSE, Mode = "configurational")
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 50, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 51, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 52, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 88, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 89, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 126, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 128, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 140, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 145, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 146, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 81, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 92, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 93, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 116, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 117, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 118, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 127, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 131, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 138, Chain = "X", Graphics = TRUE)
Dynamic_configurational <- dynamic_res(Dynamic = Dynamic_configurational, Resno = 139, Chain = "X", Graphics = TRUE)
